# Default GitHub labels
- color: d73a4a
  name: bug
  description: "Something isn't working"
- color: cfd3d7
  name: duplicate
  description: "This issue or pull request already exists"
- color: a2eeef
  name: enhancement
  description: "New feature or request"
- color: 7057ff
  name: good first issue
  description: "Good for newcomers"
- color: 008672
  name: help wanted
  description: "Extra attention is needed"
- color: e4e669
  name: invalid
  description: "This doesn't seem right"
- color: d876e3
  name: question
  description: "Further information is requested"
- color: ffffff
  name: wontfix
  description: "This will not be worked on"

# Keep a Changelog labels
# https://keepachangelog.com/en/1.0.0/
- color: 0e8a16
  name: "changelog: Added"
  description: "For new features"
- color: af99e5
  name: "changelog: Changed"
  description: "For changes in existing functionality"
- color: FFA500
  name: "changelog: Deprecated"
  description: "For soon-to-be removed features"
- color: 00A800
  name: "changelog: Fixed"
  description: "For any bug fixes"
- color: ff0000
  name: "changelog: Removed"
  description: "For now removed features"
- color: 045aa0
  name: "changelog: Security"
  description: "In case of vulnerabilities"
- color: fbca04
  name: "changelog: skip"
  description: "Exclude PR from release draft"

# Other labels
- color: d0c1ff
  name: "needs localisation"
  description: "Translations need updating"
- color: e29673
  name: "needs tests"
- color: fbca04
  name: testing
  description: "Unit tests, linting, CI, etc."
